### ISSUE TITLE
Getting Error after origination transaction: Syncing stopped manually.

### ISSUE THREAD

**Issue by sanketnighot** [kukai-wallet/kukai#551] opened 2024-02-28 08:03 UTC
# Error Message
Unhandled Runtime Error
Error: Syncing stopped manually.

# Flow of the NextJs Application.
1. A nextJs application that has a button. 
2. When the button is clicked, the wallet connection using beacon sdk. Once the wallet is connected to kukai, the Origination of the FA2 contract transaction is to be done.
3. Wallet gets disconnected

# Issue
Once the transaction is submitted, after it gets confirmed on the blockchain the error occurs. This is happening only for kukai and not for any other wallet eg. temple wallet.

# Package versions used
"@airgap/beacon-sdk": "4.0.4"
"@taquito/beacon-wallet": "16.2.0"
"@taquito/taquito": "16.2.0"
"next": "14.0.4"

<img width="967" alt="Screenshot 2024-02-27 at 10 32 59 AM" src="https://github.com/kukai-wallet/kukai/assets/60044186/1949953e-31db-4e18-ab00-3a0306b55957">

**Comment by klassare** [comment] 2024-02-28 10:29
Please provide exact steps on how we can reproduce this issue. Is the "NextJs Application" open-source?

**Comment by sanketnighot** [comment] 2024-02-28 19:32
Yes,
You can check this code:
https://github.com/sanketnighot/sat-token-deployer-ui/blob/main/utils/origination.js#L10

**Comment by klassare** [comment] 2024-02-28 23:32
You get that error for all wallets that uses `p2p-transport` on `client.disconnect()`. Just tested against Temple Mobile to confirm this. Closing this since it is not a Kukai issue.

**Closed as completed by klassare** 2024-02-28 23:32 UTC
